// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_gddb9x-MwItHwGUHhTmYWye4sFDNJ24',
    appId: '1:310337877237:web:9871d36348b6660d5cc1bc',
    messagingSenderId: '310337877237',
    projectId: 'iotaula020625',
    authDomain: 'iotaula020625.firebaseapp.com',
    storageBucket: 'iotaula020625.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDEUHfFtzKFKgoatoG4cL08aztJ2mAUJJA',
    appId: '1:310337877237:android:bd4d5b7106bde9f25cc1bc',
    messagingSenderId: '310337877237',
    projectId: 'iotaula020625',
    storageBucket: 'iotaula020625.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC_gddb9x-MwItHwGUHhTmYWye4sFDNJ24',
    appId: '1:310337877237:web:9a56d855a5561e8f5cc1bc',
    messagingSenderId: '310337877237',
    projectId: 'iotaula020625',
    authDomain: 'iotaula020625.firebaseapp.com',
    storageBucket: 'iotaula020625.firebasestorage.app',
  );
}
